python run_summarization.py \
    --model_name_or_path t5-base \
    --do_train \
    --train_file ../train/huggingface_format.csv \
    --validation_file ../dev-0/huggingface_format.csv \
    --source_prefix "classify: " \
    --summary_column 'label' \
    --max_target_length=4 \
    --max_source_length=64 \
    --output_dir ./t5-retrained \
    --per_device_train_batch_size=16 \
    --per_device_eval_batch_size=16 \
    --overwrite_output_dir \
    --predict_with_generate \
    --save_steps=10000 \
